# Generated by Django 4.0.5 on 2022-06-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_status_tache_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='start_date',
            field=models.CharField(max_length=255),
        ),
    ]
